# Generated by Django 4.1.7 on 2023-04-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product_id", new_name="product_name",
        ),
    ]
