# Generated by Django 4.1.7 on 2023-04-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_product_id_product_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product", name="price", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
    ]
