# Generated by Django 4.1.7 on 2023-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="static/images"),
        ),
    ]
